---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogue
  namespace: shopping-microservices
  labels:
    app: productcatalogue
spec:
  type: NodePort
  selector:
    app: productcatalogue
  ports:
    - protocol: TCP
      port: 8020
      name: http

---
