---
apiVersion: v1
kind: Service
metadata:
  name: stockmanager
  namespace: default
  labels:
    app: stockmanager
spec:
  type: NodePort
  selector:
    app: stockmanager
  ports:
    - protocol: TCP
      port: 8030
      name: http

---
